spring.application.name=Booking
# Server
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username= postgres
spring.datasource.password= root

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT Configuration (Custom)
jwt.secret=eNFXCzVL9/5AaDGkm0Rg6AOk6grkZnfbkNWSaODCDvKCPGkP5tsnpt6uZp5uwCgQzaaB+WRKmTdrtW/2lGZ4vA==
jwt.expiration=3600000

# Logging for SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
